# Generated by Django 5.1.15 on 2026-10-04 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(help_text="Target job role (e.g., 'Backend Developer')", max_length=150)),
                ('target_skills', models.JSONField(blank=True, default=list, help_text='List of skills focused on during the interview session')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('total_questions', models.PositiveSmallIntegerField(default=3, help_text='Total number of questions in this interview session')),
                ('current_question_index', models.PositiveSmallIntegerField(default=0, help_text='0-indexed position of the active question')),
                ('overall_score', models.FloatField(blank=True, help_text='Average or weighted session score (0 - 100)', null=True)),
                ('summary_feedback', models.JSONField(blank=True, default=dict, help_text='Structured feedback: readiness, strengths, improvements, recommended_skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='1-based sequence order of the question in the session')),
                ('skill_focus', models.CharField(blank=True, default='', help_text='Primary technical skill or topic tested by this question', max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('question_text', models.TextField(help_text='The interview question presented to the candidate')),
                ('expected_points', models.JSONField(blank=True, default=list, help_text='Key engineering concepts or rubric points expected in a strong answer')),
                ('user_answer', models.TextField(blank=True, default='', help_text="Candidate's submitted answer text")),
                ('answered_at', models.DateTimeField(blank=True, help_text='Timestamp when the candidate submitted their answer', null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Evaluated score for this question (0 - 100)', null=True)),
                ('evaluation', models.JSONField(blank=True, default=dict, help_text='Structured feedback: technical_accuracy, depth, strengths, improvements, ideal_answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'db_table': 'interview_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['user', '-created_at'], name='is_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['status'], name='is_status_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['session', 'order'], name='iq_session_order_idx'),
        ),
    ]
