# Generated by Django 5.1.15 on 2026-10-04 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(db_index=True, help_text="Normalized lowercase skill name (e.g., 'python', 'react', 'docker')", max_length=100)),
                ('skill_category', models.CharField(blank=True, default='', help_text="Skill category (e.g., 'Programming Language', 'Framework', 'DevOps')", max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=500)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('freecodecamp', 'freeCodeCamp'), ('mdn', 'MDN Web Docs'), ('w3schools', 'W3Schools'), ('geeksforgeeks', 'GeeksforGeeks'), ('roadmap_sh', 'roadmap.sh'), ('realpython', 'Real Python'), ('official_docs', 'Official Documentation'), ('github', 'GitHub'), ('coursera', 'Coursera'), ('khan_academy', 'Khan Academy'), ('other', 'Other')], default='other', max_length=30)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('tutorial', 'Tutorial'), ('documentation', 'Documentation'), ('video', 'Video'), ('article', 'Article'), ('interactive', 'Interactive Exercise'), ('project', 'Project-Based')], default='tutorial', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated completion time in hours', max_digits=5, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Resource',
                'verbose_name_plural': 'Learning Resources',
                'db_table': 'learning_resources',
                'ordering': ['skill_name', 'difficulty', 'platform'],
                'indexes': [models.Index(fields=['skill_name', 'is_active'], name='lr_skill_active_idx'), models.Index(fields=['skill_category'], name='lr_category_idx')],
            },
        ),
    ]
