# Generated by Django 5.1.15 on 2026-09-23 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('company', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location_country', models.CharField(blank=True, default='IN', max_length=10)),
                ('is_remote', models.BooleanField(db_index=True, default=False)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('posted_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source_url', models.URLField(max_length=1024)),
                ('source_provider', models.CharField(db_index=True, default='adzuna', max_length=50)),
                ('source_id', models.CharField(max_length=255)),
                ('dedup_hash', models.CharField(db_index=True, help_text='SHA-256 fingerprint for cross-provider duplicate detection.', max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original unparsed JSON payload from provider.')),
                ('extracted_skills', models.JSONField(blank=True, default=list, help_text='List of technical/soft skills identified by the NER pipeline.')),
                ('extracted_role', models.CharField(blank=True, help_text='Canonical role category determined by entity extraction.', max_length=255)),
                ('is_processed', models.BooleanField(db_index=True, default=False, help_text='True if NER extraction and downstream graph/vector indexing have succeeded.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-posted_date', '-created_at'],
                'indexes': [models.Index(fields=['is_processed', 'created_at'], name='jobs_jobpos_is_proc_576de4_idx'), models.Index(fields=['location_city', 'category'], name='jobs_jobpos_locatio_c8fb84_idx'), models.Index(fields=['title', 'company'], name='jobs_jobpos_title_9c812f_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_provider', 'source_id'), name='unique_provider_source_id')],
            },
        ),
    ]
